export const chineseCities = [
    { value: "Аксу", label: "Аксу" },
    { value: "Алтай", label: "Алтай" },
    { value: "Аньда", label: "Аньда" },
    { value: "Аньцю", label: "Аньцю" },
    { value: "Анькан", label: "Анькан" },
    { value: "Аньцин", label: "Аньцин" },
    { value: "Аньян", label: "Аньян" },
    { value: "Баодин", label: "Баодин" },
    { value: "Баоцзи", label: "Баоцзи" },
    { value: "Бухэ", label: "Бухэ" },
    { value: "Вэйфан", label: "Вэйфан" },
    { value: "Гаосюн", label: "Гаосюн" },
    { value: "Далянь", label: "Далянь" },
    { value: "Датун", label: "Датун" },
    { value: "Ичан", label: "Ичан" },
    { value: "Кашгар", label: "Кашгар" },
    { value: "Макао", label: "Макао" },
    { value: "Наньпин", label: "Наньпин" },
    { value: "Пекин", label: "Пекин" },
    { value: "Санья", label: "Санья" },
    { value: "Ухань", label: "Ухань" },
    { value: "Харбин", label: "Харбин" },
    { value: "Шанхай", label: "Шанхай" },
    { value: "Яньцзи", label: "Яньцзи" },

];